# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TuistEx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TuistEx

  target 'TuistExKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TuistExTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TuistExUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TuistExKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TuistExKit

  target 'TuistExKitTests' do
    # Pods for testing
  end

end

target 'TuistExUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TuistExUI

  target 'TuistExUITests' do
    # Pods for testing
  end

end
